=== bryantaustin13/cql-tests/tests/testSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://hl7.org/fhirpath/tests"
		   xmlns="http://hl7.org/fhirpath/tests"
		   elementFormDefault="qualified">
	<xs:element name="tests" type="Tests"/>
	<xs:complexType name="TestCapability">
		<xs:annotation>
			<xs:documentation>
				Declares a capability under test. 'code' is a code from the CQL Language Capability Codes
				CodeSystem; 'value' (optional) is a qualifier that follows the code's valueMeaning.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="code" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Capability code (e.g., 'decimal-precision-and-scale'). Must be from the CQL Capability Codes.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Optional qualifier value (format/allowed values per the code's valueMeaning).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Tests">
		<xs:annotation>
			<xs:documentation>The Tests type provides a container for test suites made up of groups of tests.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<!-- New: suite-level capabilities -->
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) that apply to the entire test suite unless overridden by Group or Test.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test suite.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="group" type="Group" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test suite. This should be a computer-friendly name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to the specification under test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Group">
		<xs:sequence>
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) that apply to all tests in this group unless overridden by a Test.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test group.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="test" type="Test" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test group. This should be a computer-friendly name and must be unique within the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test group.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to area of the specification under that the tests in this group cover.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Test">
		<xs:sequence>
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) specific to this test. These override Group/Tests level when conflicting.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="expression" type="Expression">
				<xs:annotation>
					<xs:documentation>The expression to be tested.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="output" type="Output" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The expected output of the test.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test. These notes should be included with the test output if the test fails.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test suite. This should be a computer-friendly name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skipStaticCheck" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Indicates whether to skip static type-checking as part of the test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ordered" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Indicates whether to check order of results (i.e. list equality vs collection equality).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mode" type="ModeType">
			<xs:annotation>
				<xs:documentation>Indicates whether the test should be evaluated with strict (e.g. Patient.deceased) as opposed to lenient (e.g. Patient.deceasedBoolean) semantics.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to the specification under test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="inputfile" type="xs:string">
			<xs:annotation>
				<xs:documentation>If present, the name of an input file containing input data for the test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="predicate" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>True if this test represents a predicate.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Expression">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="invalid" type="InvalidType">
					<xs:annotation>
						<xs:documentation>Indicates whether the expression is expected to evaluate successfully, produce a runtime error, or produce a semantic error.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Output">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="OutputType" use="optional">
					<xs:annotation>
						<xs:documentation>The type of the expected output. If output type is not present, the content of the output is the string representation of a literal (e.g. 10.0)</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="OutputType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="code"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="dateTime"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="id"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="Quantity"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="time"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="InvalidType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false">
				<xs:annotation><xs:documentation>Indicates the test is expected to evaluate successfully.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="syntax">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a syntax error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="semantic">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a semantic error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="execution">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce an execution error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="true">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a runtime error.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="strict">
				<xs:annotation><xs:documentation>Indicates the test is expected to evaluated with strict semantics (i.e. paths for choice-valued elements do not include the type name (e.g. Patient.deceased, not Patient.deceasedBoolean)).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="lenient">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with lenient semantics (i.e. paths for choice-valued elements may be included (e.g. Patient.deceasedBoolean)).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="lenient/polymorphics">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with lenient, as well as polymorphic, semantics (i.e. paths for choice-valued elements may be included, as well as the ability to treat the choice-valued elements polymorphically).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="element">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with respect to a particular element (i.e. from the context of a particular element such as an invariant evaluation).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="cda">
				<xs:annotation><xs:documentation>Indicates the test is evaluating a CDA document, as opposed to a FHIR resource.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="tx">
				<xs:annotation><xs:documentation>Indicates the test is expected to have access to the %terminologies environment variable, allowing access to terminology services as described in the FHIRPath topic in the FHIR specification.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bryantaustin13/cql-tests/tests/cql/CqlConditionalOperatorsTest.xml
<?xml version="1.0" encoding="utf-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://hl7.org/fhirpath/tests" xsi:schemaLocation="http://hl7.org/fhirpath/tests ../../testSchema/testSchema.xsd"
	name="CqlConditionalOperatorsTest" reference="https://cql.hl7.org/03-developersguide.html#conditional-expressions" version="1.0">
	<capability code="logical-operators"/>
	<capability code="comparison-operators"/>
	<capability code="arithmetic-operators"/>
	<group name="if-then-else" version="1.0">
		<capability code="logical-operators"/>
		<capability code="comparison-operators"/>
		<capability code="arithmetic-operators"/>
		<test name="IfTrue1" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>if 10 &gt; 5 then 5 else 10</expression>
			<output>5</output>
		</test>
		<test name="IfFalse1" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>if 10 = 5 then 10 + 5 else 10 - 5</expression>
			<output>5</output>
		</test>
		<test name="IfNull1" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>if 10 = null then 5 else 10</expression>
			<output>10</output>
		</test>
		<test name="IfNullCondition" version="1.0">
			<!-- null condition is interpreted as false, so the else branch is taken -->
			<expression>if null as Boolean then 5 else 10</expression>
			<output>10</output>
		</test>
		<test name="IfNested" version="1.0">
			<expression>if true then (if false then 1 else 2) else 3</expression>
			<output>2</output>
		</test>
	</group>
	<group name="standard case" version="1.0">
		<capability code="logical-operators"/>
		<capability code="comparison-operators"/>
		<capability code="arithmetic-operators"/>
		<test name="StandardCase1" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case
					when 10 &gt; 5 then 5
					when 5 &gt; 10 then 10
					else null
				end
			</expression>
			<output>5</output>
		</test>
		<test name="StandardCase2" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case
					when 5 &gt; 10 then 5 + 10
					when 5 = 10 then 10
					else 10 - 5
				end
			</expression>
			<output>5</output>
		</test>
		<test name="StandardCase3" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case
					when null ~ 10 then null + 10
					when null ~ 5 then 5
					else 5 + 10
				end
			</expression>
			<output>15</output>
		</test>
		<test name="StandardCaseNullCondition" version="1.0">
			<!-- a when condition that evaluates to null is interpreted as false -->
			<expression>case when null as Boolean then 1 else 2 end</expression>
			<output>2</output>
		</test>
	</group>
	<group name="selected case" version="1.0">
		<capability code="logical-operators"/>
		<capability code="comparison-operators"/>
		<capability code="arithmetic-operators"/>
		<test name="SelectedCase1" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case 5
					when 5 then 12
					when 10 then 10 + 5
					else 10 - 5
				end
			</expression>
			<output>12</output>
		</test>
		<test name="SelectedCase2" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case 10
					when 5 then 12
					when 10 then 10 + 5
					else 10 - 5
				end
			</expression>
			<output>15</output>
		</test>
		<test name="SelectedCase3" version="1.0">
			<capability code="logical-operators"/>
			<capability code="comparison-operators"/>
			<capability code="arithmetic-operators"/>
			<expression>
				case 10 + 5
					when 5 then 12
					when 10 then 10 + 5
					else 10 - 5
				end
			</expression>
			<output>5</output>
		</test>
		<test name="SelectedCaseNullComparand" version="1.0">
			<!-- a null comparand compares equal to nothing, so the else result is returned -->
			<expression>case (null as Integer) when 5 then 12 when 10 then 15 else 0 end</expression>
			<output>0</output>
		</test>
		<test name="SelectedCaseNullWhen" version="1.0">
			<!-- a null case item does not compare equal to the comparand -->
			<expression>case 5 when (null as Integer) then 12 when 5 then 99 else 0 end</expression>
			<output>99</output>
		</test>
	</group>
</tests>

=== bryantaustin13/cql-tests/tests/cql/CqlErrorsAndMessagingOperatorsTest.xml
<?xml version="1.0" encoding="utf-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://hl7.org/fhirpath/tests" xsi:schemaLocation="http://hl7.org/fhirpath/tests ../../testSchema/testSchema.xsd" name="CqlErrorsAndMessagingOperatorsTest" reference="https://cql.hl7.org/09-b-cqlreference.html#errors-and-messaging" version="1.0">
	<capability code="diagnostic-operators"/>
	<group name="Messaging" version="1.0">
		<capability code="diagnostic-operators"/>
		<test name="TestMessageInfo" version="1.0">
      		<capability code="diagnostic-operators"/>
			<expression>Message(1, true, '100', 'Message', 'Test Message')</expression>
			<output>1</output>
		</test>
		<test name="TestMessageWarn" version="1.0">
      		<capability code="diagnostic-operators"/>
			<expression>Message(2, true, '200', 'Warning', 'You have been warned!')</expression>
			<output>2</output>
		</test>
		<test name="TestMessageTrace" version="1.0">
      		<capability code="diagnostic-operators"/>
			<expression>Message({3, 4, 5}, true, '300', 'Trace', 'This is a trace')</expression>
			<output>{3, 4, 5}</output>
		</test>
		<test name="TestMessageError" version="1.0">
      		<capability code="diagnostic-operators"/>
			<expression invalid="true">Message(3 + 1, true, '400', 'Error', 'This is an error!')</expression>
			<!-- EXPECT: 400: This is an error! -->
		</test>
		<test name="TestMessageConditionFalse" version="1.0">
			<capability code="diagnostic-operators"/>
			<!-- condition false: message is not generated, source is returned -->
			<expression>Message(5, false, '100', 'Message', 'not generated')</expression>
			<output>5</output>
		</test>
		<test name="TestMessageErrorConditionFalse" version="1.0">
			<capability code="diagnostic-operators"/>
			<!-- condition false: even Error severity does not stop evaluation; source is returned (contrast with TestMessageError) -->
			<expression>Message(5, false, '400', 'Error', 'not raised')</expression>
			<output>5</output>
		</test>
		<test name="TestMessageNullSource" version="1.0">
			<capability code="diagnostic-operators"/>
			<!-- source is returned unchanged, including null -->
			<expression>Message(null as Integer, true, '100', 'Message', 'null source')</expression>
			<output>null</output>
		</test>
	</group>
</tests>

=== bryantaustin13/cql-tests/tests/cql/CqlAggregateTest.xml
<?xml version="1.0" encoding="utf-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://hl7.org/fhirpath/tests" xsi:schemaLocation="http://hl7.org/fhirpath/tests ../../testSchema/testSchema.xsd"
	name="CqlAggregateTest" reference="http://build.fhir.org/ig/HL7/cql/03-developersguide.html#aggregate-queries" version="1.5">
	<capability code="aggregate-clause-query"/>
	<group name="AggregateTests" version="1.5">
		<capability code="aggregate-clause-query"/>
		<test name="FactorialOfFive" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>({ 1, 2, 3, 4, 5 }) Num aggregate Result starting 1: Result * Num</expression>
			<output>120</output>
		</test>
		<test name="RolledOutIntervals" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				({
				  Interval[@2012-01-01, @2012-02-28],
				  Interval[@2012-02-01, @2012-03-31],
				  Interval[@2012-03-01, @2012-04-30]
				}) M
				  aggregate R starting (null as List&lt;Interval&lt;DateTime>>): R union ({
				    M X
				      let S: Max({ end of Last(R) + 1 day, start of X }),
				        E: S + Quantity{ value: duration in days of X, unit: 'days' }
				      return Interval[S, E]
				  })
			</expression>
			<output>
				{
				  Interval[@2012-01-01, @2012-02-28],
				  Interval[@2012-02-29, @2012-04-28],
				  Interval[@2012-04-29, @2012-06-28]
				}
			</output>
		</test>
		<test name="AggregateSumWithStart" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				({ 1, 2, 3, 4, 5 }) Num
				  aggregate Result starting 1: Result + Num
			</expression>
			<output>16</output>
			<!-- 15 + 1 (the initial value) -->
		</test>
		<test name="AggregateSumWithNull" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				({ 1, 2, 3, 4, 5 }) Num
				  aggregate Result: Coalesce(Result, 0) + Num
			</expression>
			<output>15</output>
			<!-- 15 + 0 (the initial value from null) -->
		</test>
		<test name="AggregateSumAll" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				({ 1, 1, 2, 2, 2, 3, 4, 4, 5 }) Num
				  aggregate all Result: Coalesce(Result, 0) + Num
			</expression>
			<output>24</output>
			<!-- 24 + 0 -->
		</test>
		<test name="AggregateSumDistinct" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				({ 1, 1, 2, 2, 2, 3, 4, 4, 5 }) Num
				  aggregate distinct Result: Coalesce(Result, 0) + Num
			</expression>
			<output>15</output>
			<!-- 15 + 0 (the initial value) -->
		</test>
		<test name="Multi" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				from ({1}) X, ({2}) Y, ({3}) Z
				  aggregate Agg: Coalesce(Agg, 0) + X + Y + Z
			</expression>
			<output>6</output>
		</test>
		<test name="MegaMulti" version="1.5">
			<capability code="multi-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				from ({1, 2}) X, ({1, 2}) Y, ({1, 2}) Z
				  aggregate Agg starting 0: Agg + X + Y + Z
			</expression>
			<output>36</output>
			<!-- (1+1+1)+(1+1+2)+(1+2+1)+(1+2+2)+(2+1+1)+(2+1+2)+(2+2+1)+(2+2+2) -->
		</test>
		<test name="MegaMultiDistinct" version="1.5">
			<capability code="multi-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>
				from ({1, 2, 2, 1}) X, ({1, 2, 1, 2}) Y, ({2, 1, 2, 1}) Z
				  aggregate distinct Agg starting 1: Agg + X + Y + Z
			</expression>
			<output>37</output>
			<!-- 1 + (1+1+1)+(1+1+2)+(1+2+1)+(1+2+2)+(2+1+1)+(2+1+2)+(2+2+1)+(2+2+2) -->
		</test>
		<test name="AggregateEmptySourceWithStart" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<!-- empty source: no iterations, so the accumulator keeps its starting value -->
			<expression>({ } as List&lt;Integer&gt;) Num aggregate Result starting 5: Result + Num</expression>
			<output>5</output>
		</test>
		<test name="AggregateEmptySourceNoStart" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<!-- empty source with no starting clause: accumulator stays at its initial null -->
			<expression>({ } as List&lt;Integer&gt;) Num aggregate Result: Coalesce(Result, 0) + Num</expression>
			<output>null</output>
		</test>
		<test name="AggregateDecimal" version="1.5">
			<capability code="single-source-query"/>
			<capability code="aggregate-clause-query"/>
			<expression>({ 1.0, 2.0, 3.0 }) Num aggregate Result starting 0.0: Result + Num</expression>
			<output>6.0</output>
		</test>
	</group>
</tests>
