=== bryantaustin13/cql-tests/tests/testSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://hl7.org/fhirpath/tests"
		   xmlns="http://hl7.org/fhirpath/tests"
		   elementFormDefault="qualified">
	<xs:element name="tests" type="Tests"/>
	<xs:complexType name="TestCapability">
		<xs:annotation>
			<xs:documentation>
				Declares a capability under test. 'code' is a code from the CQL Language Capability Codes
				CodeSystem; 'value' (optional) is a qualifier that follows the code's valueMeaning.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="code" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Capability code (e.g., 'decimal-precision-and-scale'). Must be from the CQL Capability Codes.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Optional qualifier value (format/allowed values per the code's valueMeaning).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Tests">
		<xs:annotation>
			<xs:documentation>The Tests type provides a container for test suites made up of groups of tests.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<!-- New: suite-level capabilities -->
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) that apply to the entire test suite unless overridden by Group or Test.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test suite.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="group" type="Group" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test suite. This should be a computer-friendly name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to the specification under test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Group">
		<xs:sequence>
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) that apply to all tests in this group unless overridden by a Test.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test group.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="test" type="Test" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test group. This should be a computer-friendly name and must be unique within the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test group.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to area of the specification under that the tests in this group cover.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Test">
		<xs:sequence>
			<xs:element name="capability" type="TestCapability" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Capability(ies) specific to this test. These override Group/Tests level when conflicting.
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			<xs:element name="expression" type="Expression">
				<xs:annotation>
					<xs:documentation>The expression to be tested.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="output" type="Output" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The expected output of the test.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Notes about the test. These notes should be included with the test output if the test fails.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the test suite. This should be a computer-friendly name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skipStaticCheck" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Indicates whether to skip static type-checking as part of the test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ordered" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Indicates whether to check order of results (i.e. list equality vs collection equality).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mode" type="ModeType">
			<xs:annotation>
				<xs:documentation>Indicates whether the test should be evaluated with strict (e.g. Patient.deceased) as opposed to lenient (e.g. Patient.deceasedBoolean) semantics.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string">
			<xs:annotation>
				<xs:documentation>The version of FHIRPath in which the features being tested were introduced. This should correspond to a published or planned published version of FHIRPath.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="versionTo" type="xs:string">
			<xs:annotation>
				<xs:documentation>The last version of the specification in which the features being tested appears</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>A description of the test suite.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="reference" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>A reference to the specification under test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="inputfile" type="xs:string">
			<xs:annotation>
				<xs:documentation>If present, the name of an input file containing input data for the test.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="predicate" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>True if this test represents a predicate.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Expression">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="invalid" type="InvalidType">
					<xs:annotation>
						<xs:documentation>Indicates whether the expression is expected to evaluate successfully, produce a runtime error, or produce a semantic error.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Output">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="OutputType" use="optional">
					<xs:annotation>
						<xs:documentation>The type of the expected output. If output type is not present, the content of the output is the string representation of a literal (e.g. 10.0)</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="OutputType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="code"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="dateTime"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="id"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="Quantity"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="time"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="InvalidType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false">
				<xs:annotation><xs:documentation>Indicates the test is expected to evaluate successfully.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="syntax">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a syntax error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="semantic">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a semantic error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="execution">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce an execution error.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="true">
				<xs:annotation><xs:documentation>Indicates the test is expected to produce a runtime error.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="strict">
				<xs:annotation><xs:documentation>Indicates the test is expected to evaluated with strict semantics (i.e. paths for choice-valued elements do not include the type name (e.g. Patient.deceased, not Patient.deceasedBoolean)).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="lenient">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with lenient semantics (i.e. paths for choice-valued elements may be included (e.g. Patient.deceasedBoolean)).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="lenient/polymorphics">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with lenient, as well as polymorphic, semantics (i.e. paths for choice-valued elements may be included, as well as the ability to treat the choice-valued elements polymorphically).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="element">
				<xs:annotation><xs:documentation>Indicates the test is expected to be evaluated with respect to a particular element (i.e. from the context of a particular element such as an invariant evaluation).</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="cda">
				<xs:annotation><xs:documentation>Indicates the test is evaluating a CDA document, as opposed to a FHIR resource.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="tx">
				<xs:annotation><xs:documentation>Indicates the test is expected to have access to the %terminologies environment variable, allowing access to terminology services as described in the FHIRPath topic in the FHIR specification.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bryantaustin13/cql-tests/tests/cql/CqlNullologicalOperatorsTest.xml
<?xml version="1.0" encoding="utf-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://hl7.org/fhirpath/tests" xsi:schemaLocation="http://hl7.org/fhirpath/tests ../../testSchema/testSchema.xsd"
	name="CqlNullologicalOperatorsTest" reference="https://cql.hl7.org/09-b-cqlreference.html#nullological-operators-3" version="1.0">
	<capability code="nullological-operators" />
	<group name="Coalesce" version="1.0">
		<capability code="nullological-operators" />
		<test name="CoalesceANull" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce('a', null)</expression>
			<output>'a'</output>
		</test>
		<test name="CoalesceNullA" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce(null, 'a')</expression>
			<output>'a'</output>
		</test>
		<test name="CoalesceEmptyList" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({})</expression>
			<output>null</output>
		</test>
		<test name="CoalesceListFirstA" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({'a', null, null})</expression>
			<output>'a'</output>
		</test>
		<test name="CoalesceListLastA" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({null, null, 'a'})</expression>
			<output>'a'</output>
		</test>
		<test name="CoalesceFirstList" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({'a'},null, null)</expression>
			<output>{'a'}</output>
		</test>
		<test name="CoalesceLastList" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce(null, null, {'a'})</expression>
			<output>{'a'}</output>
		</test>
		<test name="DateTimeCoalesce" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce(null, null, DateTime(2012, 5, 18))</expression>
			<output>@2012-05-18T</output>
		</test>
		<test name="DateTimeListCoalesce" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({ null, null, DateTime(2012, 5, 18) })</expression>
			<output>@2012-05-18T</output>
		</test>
		<test name="TimeCoalesce" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce(null, null, @T05:15:33.556)</expression>
			<output>@T05:15:33.556</output>
		</test>
		<test name="TimeListCoalesce" version="1.0">
			<capability code="nullological-operators" />
			<expression>Coalesce({ null, null, @T05:15:33.556 })</expression>
			<output>@T05:15:33.556</output>
		</test>
		<test name="Coalesce15" version="1.0">
			<capability code="nullological-operators" />
			<!-- returns the first non-null result; per CQL spec "Coalesce" (https://cql.hl7.org/09-b-cqlreference.html#coalesce) -->
			<expression>Coalesce(null, 15, null)</expression>
			<output>15</output>
		</test>
		<test name="CoalesceFourArgs" version="1.0">
			<capability code="nullological-operators" />
			<!-- 4-argument overload; per CQL spec "Coalesce" (https://cql.hl7.org/09-b-cqlreference.html#coalesce) -->
			<expression>Coalesce(null, null, null, 'd')</expression>
			<output>'d'</output>
		</test>
		<test name="CoalesceFiveArgs" version="1.0">
			<capability code="nullological-operators" />
			<!-- 5-argument overload; per CQL spec "Coalesce" (https://cql.hl7.org/09-b-cqlreference.html#coalesce) -->
			<expression>Coalesce(null, null, null, null, 'e')</expression>
			<output>'e'</output>
		</test>
		<test name="CoalesceAllNullList" version="1.0">
			<capability code="nullological-operators" />
			<!-- all arguments null => null; per CQL spec "Coalesce" (https://cql.hl7.org/09-b-cqlreference.html#coalesce) -->
			<expression>Coalesce({ null, null, null })</expression>
			<output>null</output>
		</test>
		<test name="CoalesceMoreThanFiveArgs" version="1.0">
			<capability code="nullological-operators" />
			<!-- invalid: more than 5 inputs must be represented as a list, so there is no matching overload; per CQL spec "Coalesce" (https://cql.hl7.org/09-b-cqlreference.html#coalesce): "more than 5 inputs must be represented as list" -->
			<expression invalid="semantic">Coalesce(null, 15, null, null, null, null)</expression>
		</test>
	</group>
	<group name="IsNull" version="1.0">
		<capability code="nullological-operators" />
		<test name="IsNullTrue" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsNull(null)</expression>
			<output>true</output>
		</test>
		<test name="IsNullFalseEmptyString" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsNull('')</expression>
			<output>false</output>
		</test>
		<test name="IsNullAlsoFalseAbcString" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsNull('abc')</expression>
			<output>false</output>
		</test>
		<test name="IsNullAlsoFalseNumber1" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsNull(1)</expression>
			<output>false</output>
		</test>
		<test name="IsNullAlsoFalseNumberZero" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsNull(0)</expression>
			<output>false</output>
		</test>
		<test name="IsNullOperatorTrue" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsNull" (https://cql.hl7.org/09-b-cqlreference.html#isnull) -->
			<expression>null is null</expression>
			<output>true</output>
		</test>
		<test name="IsNullOperatorFalse" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsNull" (https://cql.hl7.org/09-b-cqlreference.html#isnull) -->
			<expression>'abc' is null</expression>
			<output>false</output>
		</test>
	</group>
	<group name="IsFalse" version="1.0">
		<capability code="nullological-operators" />
		<test name="IsFalseFalse" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsFalse(false)</expression>
			<output>true</output>
		</test>
		<test name="IsFalseTrue" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsFalse(true)</expression>
			<output>false</output>
		</test>
		<test name="IsFalseNull" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsFalse(null)</expression>
			<output>false</output>
		</test>
		<test name="IsFalseOperatorTrue" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsFalse" (https://cql.hl7.org/09-b-cqlreference.html#isfalse) -->
			<expression>false is false</expression>
			<output>true</output>
		</test>
		<test name="IsFalseOperatorFalse" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsFalse" (https://cql.hl7.org/09-b-cqlreference.html#isfalse) -->
			<expression>true is false</expression>
			<output>false</output>
		</test>
		<test name="IsFalseOperatorNull" version="1.0">
			<capability code="nullological-operators" />
			<!-- null is not false => false; per CQL spec "IsFalse" (https://cql.hl7.org/09-b-cqlreference.html#isfalse) -->
			<expression>null is false</expression>
			<output>false</output>
		</test>
	</group>
	<group name="IsTrue" version="1.0">
		<capability code="nullological-operators" />
		<test name="IsTrueTrue" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsTrue(true)</expression>
			<output>true</output>
		</test>
		<test name="IsTrueFalse" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsTrue(false)</expression>
			<output>false</output>
		</test>
		<test name="IsTrueNull" version="1.0">
			<capability code="nullological-operators" />
			<expression>IsTrue(null)</expression>
			<output>false</output>
		</test>
		<test name="IsTrueOperatorTrue" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsTrue" (https://cql.hl7.org/09-b-cqlreference.html#istrue) -->
			<expression>true is true</expression>
			<output>true</output>
		</test>
		<test name="IsTrueOperatorFalse" version="1.0">
			<capability code="nullological-operators" />
			<!-- operator syntax (spec canonical form); per CQL spec "IsTrue" (https://cql.hl7.org/09-b-cqlreference.html#istrue) -->
			<expression>false is true</expression>
			<output>false</output>
		</test>
		<test name="IsTrueOperatorNull" version="1.0">
			<capability code="nullological-operators" />
			<!-- null is not true => false; per CQL spec "IsTrue" (https://cql.hl7.org/09-b-cqlreference.html#istrue) -->
			<expression>null is true</expression>
			<output>false</output>
		</test>
	</group>
</tests>

=== bryantaustin13/cql-tests/tests/cql/CqlQueryTests.xml
<?xml version="1.0" encoding="utf-8"?>
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://hl7.org/fhirpath/tests" xsi:schemaLocation="http://hl7.org/fhirpath/tests ../../testSchema/testSchema.xsd" name="CqlQueryTest" reference="https://cql.hl7.org/02-authorsguide.html#queries" version="1.0">
    <capability code="queries" />
    <group name="SimpleQueries" version="1.0">
        <capability code="queries" />
        <test name="NonListSource" version="1.0">
            <capability code="queries" />
            <expression>(4) l</expression>
            <output>4</output>
        </test>
        <test name="NonListSourceWithReturn" version="1.0">
            <capability code="queries" />
            <expression>(4) l return 'Hello World'</expression>
            <output>'Hello World'</output>
        </test>
        <test name="MultiSource" version="1.0">
            <capability code="queries" />
            <expression>from ({2, 3}) A, ({5, 6}) B</expression>
            <output>{{ A: 2, B: 5 }, { A: 2, B: 6 }, { A: 3, B: 5 }, { A: 3, B: 6 }}</output>
        </test>
    </group>
    <group name="Where" version="1.0">
        <capability code="queries" />
        <test name="WhereFilter" version="1.0">
            <capability code="queries" />
            <!-- where filters the source to elements for which the condition is true; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3, 4, 5}) N where N &gt; 3</expression>
            <output>{4, 5}</output>
        </test>
        <test name="WhereNoMatch" version="1.0">
            <capability code="queries" />
            <!-- no element satisfies the condition => empty list; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3}) N where N &gt; 10</expression>
            <output>{}</output>
        </test>
    </group>
    <group name="Let" version="1.0">
        <capability code="queries" />
        <test name="LetClause" version="1.0">
            <capability code="queries" />
            <!-- let introduces a query-scoped definition usable in later clauses; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3}) N let Y: N + 1 return Y</expression>
            <output>{2, 3, 4}</output>
        </test>
    </group>
    <group name="Return" version="1.0">
        <capability code="queries" />
        <test name="ReturnExpression" version="1.0">
            <capability code="queries" />
            <!-- return reshapes each element via an expression; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3}) N return N * 2</expression>
            <output>{2, 4, 6}</output>
        </test>
        <test name="ReturnDistinctDefault" version="1.0">
            <capability code="queries" />
            <!-- the default for return clauses is distinct, so duplicates are eliminated; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries): "the default for return clauses is distinct, as opposed to all" -->
            <expression>({1, 1, 2, 2, 3}) N return N</expression>
            <output>{1, 2, 3}</output>
        </test>
        <test name="ReturnAll" version="1.0">
            <capability code="queries" />
            <!-- return all keeps duplicates; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries): "the default for return clauses is distinct, as opposed to all" -->
            <expression>({1, 1, 2, 2, 3}) N return all N</expression>
            <output>{1, 1, 2, 2, 3}</output>
        </test>
    </group>
    <group name="With" version="1.0">
        <capability code="queries" />
        <test name="WithSuchThat" version="1.0">
            <capability code="queries" />
            <!-- with keeps primary-source elements that have at least one related element satisfying the condition; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3}) A with ({2, 3, 4}) B such that A = B</expression>
            <output>{2, 3}</output>
        </test>
    </group>
    <group name="Without" version="1.0">
        <capability code="queries" />
        <test name="WithoutSuchThat" version="1.0">
            <capability code="queries" />
            <!-- without keeps primary-source elements that have no related element satisfying the condition; per CQL Author's Guide "Queries" (https://cql.hl7.org/02-authorsguide.html#queries) -->
            <expression>({1, 2, 3}) A without ({2, 3, 4}) B such that A = B</expression>
            <output>{1}</output>
        </test>
    </group>
    <group name="Sort" version="1.0">
        <capability code="queries" />
        <test name="IntegerDescending" version="1.0">
            <capability code="queries" />
            <expression>({1, 2, 3}) l sort desc</expression>
            <output>{3, 2, 1}</output>
        </test>
        <test name="IntegerAscending" version="1.0">
            <capability code="queries" />
            <expression>({1, 3, 2}) l sort ascending</expression>
            <output>{1, 2, 3}</output>
        </test>
        <test name="DateTimeDescending" version="1.0">
            <capability code="queries" />
            <expression>({@2013-01-02T00:00:00.000Z, @2014-01-02T00:00:00.000Z, @2015-01-02T00:00:00.000Z}) l sort desc</expression>
            <output>{@2015-01-02T00:00:00.000Z, @2014-01-02T00:00:00.000Z, @2013-01-02T00:00:00.000Z}</output>
        </test>
        <test name="DateTimeAscending" version="1.0">
            <capability code="queries" />
            <expression>({@2013-01-02T00:00:00.000Z, @2015-01-02T00:00:00.000Z, @2014-01-02T00:00:00.000Z}) l sort ascending</expression>
            <output>{@2013-01-02T00:00:00.000Z, @2014-01-02T00:00:00.000Z, @2015-01-02T00:00:00.000Z}</output>
        </test>
    </group>
    <group name="Aggregate" version="1.0">
        <capability code="queries" />
        <test name="MultiplyIntegers" version="1.0">
            <capability code="queries" />
            <expression>({1, 2, 3, 3, 4}) L aggregate A starting 1: A * L</expression>
            <output>72</output>
        </test>
        <test name="MultiplyIntegersAll" version="1.0">
            <capability code="queries" />
            <expression>({1, 2, 3, 3, 4}) L aggregate all A starting 1: A * L</expression>
            <output>72</output>
        </test>
        <test name="MultiplyIntegersDistinct" version="1.0">
            <capability code="queries" />
            <expression>({1, 2, 3, 3, 4}) L aggregate distinct A starting 1: A * L</expression>
            <output>24</output>
        </test>
        <test name="MultiplyIntegersNoStartingExpression" version="1.0">
            <capability code="queries" />
            <expression>({1, 2, 3}) L aggregate A : A * L</expression>
            <output>null</output>
        </test>
        <test name="Multi-Source" version="1.0">
            <capability code="queries" />
            <expression>from ({1, 2, 3}) B, (4) C aggregate A : A + B + C</expression>
            <output>null</output>
        </test>
    </group>
</tests>
